#!/usr/bin/env python3
"""Generate a team deployment: one isolated Hermes (+ Telegram bot + web subdomain)
per person, sharing one stateless prometheus-proxy + gonka-router + Caddy.

Reads team/team.users (one person per line: id, telegram_bot_token, [gonka_key])
and the env vars DOMAIN and GONKA_API_KEY (the shared fallback key). Emits, at the
repo root: docker-compose.team.yml, Caddyfile.team, team/team.secrets.env, and a
per-person nginx conf. Run it via team.sh — you don't normally call it directly.

Isolation: each person gets their own Hermes container with its own data volume
(/opt/data = sessions, files, memory) and its own bot — nothing of theirs is shared.
The proxy and router are stateless and input-transparent, so sharing them leaks
nothing. (Mnemosyne is intentionally not in the shared chat path — see the README
for the per-person-namespace option if you want the memory layer too.)
"""
import os
import re
import sys
import secrets

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEAM = os.path.join(ROOT, "team")
USERS_FILE = os.path.join(TEAM, "team.users")

DOMAIN = os.environ.get("DOMAIN", "").strip()
SHARED_GONKA = os.environ.get("GONKA_API_KEY", "").strip()


def die(m):
    print("gen-team: " + m, file=sys.stderr)
    sys.exit(1)


def parse_users():
    if not os.path.exists(USERS_FILE):
        die(f"{USERS_FILE} not found (copy team.users.example to team.users)")
    users = []
    for ln in open(USERS_FILE, encoding="utf-8"):
        ln = ln.strip()
        if not ln or ln.startswith("#"):
            continue
        parts = ln.split()
        uid = parts[0]
        if not re.fullmatch(r"[a-z0-9]{1,20}", uid):
            die(f"bad id {uid!r} — use 1-20 lowercase letters/digits")
        bot = parts[1] if len(parts) > 1 else ""
        gonka = parts[2] if len(parts) > 2 else ""
        users.append({"id": uid, "bot": bot, "gonka": gonka or SHARED_GONKA})
    if not users:
        die("no users in team.users")
    ids = [u["id"] for u in users]
    if len(set(ids)) != len(ids):
        die("duplicate ids in team.users")
    return users


def main():
    users = parse_users()
    for u in users:
        if not u["gonka"]:
            die(f"user {u['id']} has no gonka key and GONKA_API_KEY (shared) is unset")
        if not u["bot"]:
            print(f"  note: user {u['id']} has no telegram bot token (web-only is fine)")

    # ── secrets env (generated once; keep out of git) ──
    sec = ["# generated by gen-team.py — DO NOT COMMIT (per-person secrets)"]
    for u in users:
        U = u["id"].upper()
        sec.append(f"GONKA_API_KEY_{U}={u['gonka']}")
        sec.append(f"TELEGRAM_BOT_TOKEN_{U}={u['bot']}")
        sec.append(f"HERMES_API_KEY_{U}={secrets.token_hex(24)}")
        sec.append(f"HERMES_DASHBOARD_OAUTH_CLIENT_ID_{U}=")
    open(os.path.join(TEAM, "team.secrets.env"), "w").write("\n".join(sec) + "\n")

    # ── per-person nginx conf ──
    for u in users:
        conf = ("map $http_upgrade $connection_upgrade { default upgrade; '' close; }\n\n"
                "server {\n"
                "    listen 80;\n    server_name _;\n    client_max_body_size 50m;\n"
                "    location / {\n"
                f"        proxy_pass http://hermes-{u['id']}:9119;\n"
                "        proxy_http_version 1.1;\n"
                "        proxy_set_header Host $host;\n"
                "        proxy_set_header X-Forwarded-Proto https;\n"
                "        proxy_set_header Upgrade $http_upgrade;\n"
                "        proxy_set_header Connection $connection_upgrade;\n"
                "        proxy_read_timeout 600s;\n    }\n}\n")
        open(os.path.join(TEAM, f"nginx-{u['id']}.conf"), "w").write(conf)

    # ── docker-compose.team.yml ──
    L = ["name: hermes-team", "", "volumes:"]
    for u in users:
        L += [f"  hermes_{u['id']}_data: {{}}", f"  hermes_{u['id']}_projects: {{}}"]
    L += ["  caddy_data: {}", "  caddy_config: {}", "", "services:"]

    # shared stateless layers
    L += [
        "  prometheus-proxy:",
        "    build: ./prometheus",
        "    image: prometheus-proxy:latest",
        "    container_name: prometheus-proxy",
        "    restart: unless-stopped",
        "    environment:",
        '      UPSTREAM_BASE_URL: "https://proxy.gonka.gg"',
        '      LOGDIR: "/log"',
        '      PROM_MAX_TOKENS: "32000"',
        '      PROM_READ_TIMEOUT: "300"',
        "    volumes:",
        "      - ./prometheus/log:/log",
        "",
        "  gonka-router:",
        "    build: ./gonka-router",
        "    image: gonka-router:latest",
        "    container_name: gonka-router",
        "    restart: unless-stopped",
        "",
        "  caddy:",
        "    image: caddy:2-alpine",
        "    container_name: caddy",
        "    restart: unless-stopped",
        "    ports:",
        '      - "80:80"',
        '      - "443:443"',
        "    volumes:",
        "      - ./Caddyfile.team:/etc/caddy/Caddyfile:ro",
        "      - caddy_data:/data",
        "      - caddy_config:/config",
        "    environment:",
        '      DOMAIN: "${DOMAIN:-}"',
    ]

    # per-person hermes + web
    for u in users:
        i, U = u["id"], u["id"].upper()
        L += [
            "",
            f"  hermes-{i}:",
            "    image: nousresearch/hermes-agent:latest",
            f"    container_name: hermes-{i}",
            "    restart: unless-stopped",
            "    environment:",
            f'      GONKA_API_KEY: "${{GONKA_API_KEY_{U}}}"',
            '      API_SERVER_ENABLED: "true"',
            '      API_SERVER_HOST: "0.0.0.0"',
            f'      API_SERVER_KEY: "${{HERMES_API_KEY_{U}}}"',
            f'      HERMES_API_KEY: "${{HERMES_API_KEY_{U}}}"',
            '      HERMES_STREAM_READ_TIMEOUT: "1800"',
            f'      TELEGRAM_BOT_TOKEN: "${{TELEGRAM_BOT_TOKEN_{U}}}"',
            '      HERMES_DASHBOARD: "true"',
            '      HERMES_DASHBOARD_HOST: "0.0.0.0"',
            '      HERMES_DASHBOARD_PORT: "9119"',
            '      HERMES_DASHBOARD_INSECURE: "true"',
            f'      HERMES_DASHBOARD_OAUTH_CLIENT_ID: "${{HERMES_DASHBOARD_OAUTH_CLIENT_ID_{U}:-}}"',
            "    volumes:",
            f"      - hermes_{i}_data:/opt/data",
            f"      - hermes_{i}_projects:/projects",
            "    command: gateway run",
            "    healthcheck:",
            '      test: ["CMD", "curl", "-sf", "http://localhost:9119/"]',
            "      interval: 30s",
            "      timeout: 10s",
            "      retries: 5",
            "      start_period: 25s",
            "",
            f"  web-{i}:",
            "    image: nginx:1.27-alpine",
            f"    container_name: web-{i}",
            "    restart: unless-stopped",
            "    volumes:",
            f"      - ./team/nginx-{i}.conf:/etc/nginx/conf.d/default.conf:ro",
            "    depends_on:",
            f"      - hermes-{i}",
        ]
    open(os.path.join(ROOT, "docker-compose.team.yml"), "w").write("\n".join(L) + "\n")

    # ── Caddyfile.team (one subdomain per person) ──
    if not DOMAIN:
        print("  note: DOMAIN unset — Caddy will have no sites; set DOMAIN for web access")
    C = ["{", "\temail admin@" + (DOMAIN or "example.com"), "}", ""]
    for u in users:
        host = f"hermes-{u['id']}.{DOMAIN}" if DOMAIN else f"hermes-{u['id']}.example.com"
        C += [host + " {", f"\treverse_proxy web-{u['id']}:80", "}", ""]
    open(os.path.join(ROOT, "Caddyfile.team"), "w").write("\n".join(C))

    print(f"generated: {len(users)} people ->",
          ", ".join(f"hermes-{u['id']}" for u in users))
    print("files: docker-compose.team.yml, Caddyfile.team, team/team.secrets.env, team/nginx-*.conf")


if __name__ == "__main__":
    main()
